apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - cluster-secret-store.yaml
  - external-secrets/backstage-secrets.yaml
  - external-secrets/argocd-secrets.yaml
  - external-secrets/argo-workflows-secrets.yaml
  - external-secrets/observability-secrets.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.10.5
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: external-secrets
  app.kubernetes.io/managed-by: kustomize
