apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goldilocks

resources:
  - namespace.yaml

helmCharts:
  - name: goldilocks
    repo: https://charts.fairwinds.com/stable
    version: 8.0.2
    releaseName: goldilocks
    namespace: goldilocks
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: goldilocks
  app.kubernetes.io/managed-by: kustomize
