apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - namespace.yaml
  - policies/baseline
  - policies/best-practices
  - policies/compliance
  - policies/cost
  - policies/mutations
  - policies/security
  - policies/generators
  - policies/secrets

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno
    version: 3.3.3
    releaseName: kyverno
    namespace: kyverno
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/managed-by: kustomize
