apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - namespace.yaml
  - templates-location.yaml

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.1.0
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: backstage
  app.kubernetes.io/managed-by: kustomize
