apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-labels.yaml
  - require-probes.yaml
  - require-requests-limits.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: best-practices-policies
