apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-external-secrets.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: secret-policies
