apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpa-system

resources:
  - namespace.yaml

helmCharts:
  - name: vpa
    repo: https://charts.fairwinds.com/stable
    version: 4.4.0
    releaseName: vpa
    namespace: vpa-system
    valuesFile: values.yaml
