apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - add-default-security-context.yaml
  - add-default-tolerations.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: mutation-policies
