apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-privileged-containers.yaml
  - disallow-host-namespaces.yaml
  - disallow-host-ports.yaml
  - disallow-capabilities.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: baseline-policies
