apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - namespace.yaml
  - aws-credentials.yaml
  - restore-workflow.yaml
  - disaster-recovery-runbook.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 6.0.0
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: velero
  app.kubernetes.io/managed-by: kustomize
