apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - generate-network-policy.yaml
  - generate-resource-quota.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: generators
