apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-cost-labels.yaml
  - add-cost-labels.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: cost-policies
