apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - prometheus-rules.yaml

helmCharts:
  - name: aws-node-termination-handler
    repo: https://aws.github.io/eks-charts
    version: 0.21.0
    releaseName: aws-node-termination-handler
    namespace: kube-system
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: spot-handler
  app.kubernetes.io/managed-by: kustomize
