apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: governance

resources:
  - namespace.yaml
  - drift-detection/prometheus-rules.yaml
  - drift-detection/remediation-workflow.yaml
  - deployment-windows/configmap.yaml
  - deployment-windows/cronjobs.yaml

commonLabels:
  app.kubernetes.io/part-of: governance
  app.kubernetes.io/managed-by: kustomize
