apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
  - namespace.yaml
  - analysis-templates/success-rate.yaml
  - analysis-templates/pod-health.yaml
  - rollout-templates/canary-rollout.yaml

helmCharts:
  - name: argo-rollouts
    repo: https://argoproj.github.io/argo-helm
    version: 2.37.7
    releaseName: argo-rollouts
    namespace: argo-rollouts
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: argo-rollouts
  app.kubernetes.io/managed-by: kustomize
