apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

resources:
  - namespace.yaml
  - eventbus.yaml
  - event-sources/github-webhook.yaml
  - event-sources/sqs-events.yaml
  - sensors/ci-sensor.yaml
  - sensors/release-sensor.yaml

helmCharts:
  - name: argo-events
    repo: https://argoproj.github.io/argo-helm
    version: 2.4.8
    releaseName: argo-events
    namespace: argo-events
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: argo-events
  app.kubernetes.io/managed-by: kustomize
