apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubecost

resources:
  - namespace.yaml
  - cost-reports-config.yaml
  - cost-alerts.yaml

helmCharts:
  - name: cost-analyzer
    repo: https://kubecost.github.io/cost-analyzer
    version: 2.4.2
    releaseName: kubecost
    namespace: kubecost
    valuesFile: values.yaml
