apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-liveness-probe.yaml
  - require-pdb.yaml
  - require-resource-limits.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno
  app.kubernetes.io/component: compliance-policies
