apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - project-platform.yaml
  - applicationsets/team-projects.yaml
  - applicationsets/team-namespaces.yaml
  - applicationsets/team-apps.yaml
  - notifications-cm.yaml
  - notifications-secret.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.7.5
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize
