apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

resources:
  - namespace.yaml

helmCharts:
  - name: falco
    repo: https://falcosecurity.github.io/charts
    version: 4.15.0
    releaseName: falco
    namespace: falco
    valuesFile: values.yaml

  - name: falcosidekick
    repo: https://falcosecurity.github.io/charts
    version: 0.8.0
    releaseName: falcosidekick
    namespace: falco
    valuesFile: sidekick-values.yaml
