apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scheduled-scaling.yaml

commonLabels:
  app.kubernetes.io/part-of: cost-optimization
  app.kubernetes.io/managed-by: kustomize
